seRompe = () =>{
    return 3 + z
}


try{
    seRompe()
}catch(err){
    console.error("algo se ha roto")
    console.error(err.message)
}